// Copyright © 2023 Tobias Erbsland. Web: https://erbsland.dev
// Copyright © 2023 EducateIT GmbH. Web: https://educateit.ch
//
// This program is free software: you can redistribute it and/or modify it under the terms of the
// GNU Lesser General Public License as published by the Free Software Foundation, either
// version 3 of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License along with this program.
// If not, see <https://www.gnu.org/licenses/>.
#pragma once


#include <erbsland/unittest/UnitTest.hpp>

#include <erbsland/qt/toml/InputStream.hpp>
#include <erbsland/qt/toml/Error.hpp>
#include <erbsland/qt/toml/impl/Tokenizer.hpp>

#include <QtCore/QString>

#include <vector>
#include <sstream>


using namespace erbsland::qt::toml;
using namespace erbsland::qt::toml::impl;


class TokenizerTest : public el::UnitTest {
public:
    Token token{};
    Token expectedToken{};

    auto additionalErrorMessages() -> std::string override {
        try {
            std::stringstream text;
            text << "token = " << token.toDebugString().toStdString();
            text << "\nexpectedToken = " << expectedToken.toDebugString().toStdString();
            return text.str();
        } catch (...) {
            return {"Unexpected exception"};
        }
    }

    void testRegression() {
        // This test mainly verifies if there is a change on tokenizer level how data is tokenized.
        auto filePath = unitTestExecutablePath().parent_path() / "data" / "tokenizer" / "all_tokens.toml";
        auto filePathQt = QString::fromStdString(filePath.string());
        auto inputStream = InputStream::createFromFile(filePathQt);
        auto expectedTokens = std::vector<Token>{
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::Comment, QString{}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::Comment, QString{}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key0"}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::DecimalInteger, QString{"1190280"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key1"}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::DecimalInteger, QString{"+2938981"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key2"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::DecimalInteger, QString{"-2291822"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key3"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::SingleLineString, QString{u8"text\n\\\"\r\b\t\f\ucdbf\U0001981a"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::BareKey, QString{"bare_key4"}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::SingleLineString, QString{"text\\n"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Comment, QString{}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::BareKey, QString{"bare_key5"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::MultiLineString, QString{"multi"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::BareKey, QString{"bare_key6"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::MultiLineString, QString{"multi"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::BareKey, QString{"bare_key7"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::MultiLineString, QString{"        multi"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key8"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::MultiLineString, QString{"        multi\n    "}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key9"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::MultiLineString, QString{"multi\n        multi"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key10"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::MultiLineString, QString{"multi\n        multi"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::SingleLineString, QString{"str key1"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Boolean, QString{"false"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::SingleLineString, QString{"str key2"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Boolean, QString{"true"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare"}},
            Token{TokenType::NameSeperator, QString{}},
            Token{TokenType::BareKey, QString{"key1"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Float, QString{"1.0"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::SingleLineString, QString{"bare"}},
            Token{TokenType::NameSeperator, QString{}},
            Token{TokenType::SingleLineString, QString{"key2"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Float, QString{"-1.0"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"012345"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::HexInteger, QString{"0xabCdEf92"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key12"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::HexInteger, QString{"0x12831829"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key13"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::OctalInteger, QString{"0o01234567"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key14"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::BinaryInteger, QString{"0b10000010"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key15"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Float, QString{"+1.0"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key16"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Float, QString{"3.1415"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key17"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Float, QString{"-0.01"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key18"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Float, QString{"5e+22"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key19"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Float, QString{"1e06"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key20"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Float, QString{"-2E-2"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key21"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Float, QString{"6.626e-34"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key21"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Float, QString{"inf"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key21"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Float, QString{"+inf"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key21"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Float, QString{"-inf"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key21"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Float, QString{"nan"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key21"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Float, QString{"+nan"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key21"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Float, QString{"-nan"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key21"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Float, QString{"224617.445991228"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key22"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::OffsetDateTime, QString{"1979-05-27T07:32:00Z"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key23"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::OffsetDateTime, QString{"1979-05-27T00:32:00-07:00"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key24"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::OffsetDateTime, QString{"1979-05-27T00:32:00.999999-07:00"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key25"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::OffsetDateTime, QString{"1979-05-27 07:32:00Z"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key26"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::LocalDateTime, QString{"1979-05-27T07:32:00"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key27"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::LocalDateTime, QString{"1979-05-27T00:32:00.999999"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key28"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::LocalDate, QString{"1979-05-27"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key29"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::LocalTime, QString{"07:32:00"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key30"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::LocalTime, QString{"00:32:00.999999"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key31"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::ArrayBegin, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::DecimalInteger, QString{"1"}},
            Token{TokenType::TableSeperator, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::DecimalInteger, QString{"2"}},
            Token{TokenType::TableSeperator, QString{}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::DecimalInteger, QString{"3"}},
            Token{TokenType::TableSeperator, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::ArrayEnd, QString{}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key32"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::ArrayBegin, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::SingleLineString, QString{"a"}},
            Token{TokenType::TableSeperator, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::SingleLineString, QString{"b"}},
            Token{TokenType::TableSeperator, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::SingleLineString, QString{"c"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::ArrayEnd, QString{}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key33"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::ArrayBegin, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::ArrayBegin, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::DecimalInteger, QString{"1"}},
            Token{TokenType::TableSeperator, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::DecimalInteger, QString{"2"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::ArrayEnd, QString{}},
            Token{TokenType::TableSeperator, QString{}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::ArrayBegin, QString{}},
            Token{TokenType::DecimalInteger, QString{"3"}},
            Token{TokenType::TableSeperator, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::DecimalInteger, QString{"4"}},
            Token{TokenType::TableSeperator, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::DecimalInteger, QString{"5"}},
            Token{TokenType::TableSeperator, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::ArrayEnd, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::ArrayEnd, QString{}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key34"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::ArrayBegin, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::ArrayBegin, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::DecimalInteger, QString{"1"}},
            Token{TokenType::TableSeperator, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::DecimalInteger, QString{"2"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::ArrayEnd, QString{}},
            Token{TokenType::TableSeperator, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::ArrayBegin, QString{}},
            Token{TokenType::SingleLineString, QString{"a"}},
            Token{TokenType::TableSeperator, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::SingleLineString, QString{"b"}},
            Token{TokenType::TableSeperator, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::SingleLineString, QString{"c"}},
            Token{TokenType::ArrayEnd, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::ArrayEnd, QString{}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key35"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::ArrayBegin, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::SingleLineString, QString{"text"}},
            Token{TokenType::TableSeperator, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::SingleLineString, QString{"text"}},
            Token{TokenType::TableSeperator, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::MultiLineString, QString{"text"}},
            Token{TokenType::TableSeperator, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::MultiLineString, QString{"text"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::ArrayEnd, QString{}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key36"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::ArrayBegin, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Float, QString{"0.7"}},
            Token{TokenType::TableSeperator, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Float, QString{"0.2"}},
            Token{TokenType::TableSeperator, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Float, QString{"0.5"}},
            Token{TokenType::TableSeperator, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::DecimalInteger, QString{"1"}},
            Token{TokenType::TableSeperator, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::DecimalInteger, QString{"2"}},
            Token{TokenType::TableSeperator, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::DecimalInteger, QString{"5"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::ArrayEnd, QString{}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key37"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::ArrayBegin, QString{}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::SingleLineString, QString{"Test <test@example.com>"}},
            Token{TokenType::TableSeperator, QString{}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::TableBegin, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::BareKey, QString{"name"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::SingleLineString, QString{"test"}},
            Token{TokenType::TableSeperator, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::BareKey, QString{"email"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::SingleLineString, QString{"bazqux@example.com"}},
            Token{TokenType::TableSeperator, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::BareKey, QString{"url"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::SingleLineString, QString{"https://example.com/"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::TableEnd, QString{}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::ArrayEnd, QString{}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::TableNameBegin, QString{}},
            Token{TokenType::BareKey, QString{"bare_table-1"}},
            Token{TokenType::TableNameEnd, QString{}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::TableNameBegin, QString{}},
            Token{TokenType::BareKey, QString{"bare_table-2"}},
            Token{TokenType::TableNameEnd, QString{}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key38"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::DecimalInteger, QString{"1"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key38"}},
            Token{TokenType::NameSeperator, QString{}},
            Token{TokenType::BareKey, QString{"value"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::DecimalInteger, QString{"1"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key38"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::NameSeperator, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::SingleLineString, QString{"value"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::DecimalInteger, QString{"1"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::TableNameBegin, QString{}},
            Token{TokenType::BareKey, QString{"bare"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::NameSeperator, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::BareKey, QString{"table-1"}},
            Token{TokenType::TableNameEnd, QString{}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::ArrayNameBegin, QString{}},
            Token{TokenType::BareKey, QString{"bare_list_1"}},
            Token{TokenType::ArrayNameEnd, QString{}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key38"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::DecimalInteger, QString{"1"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"bare_key38"}},
            Token{TokenType::NameSeperator, QString{}},
            Token{TokenType::BareKey, QString{"value"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::DecimalInteger, QString{"1"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"-bare_key40"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::DecimalInteger, QString{"1"}},
            Token{TokenType::NewLine, QString{}},
            Token{TokenType::BareKey, QString{"_bare_key41"}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::Assignment, QString{}},
            Token{TokenType::Whitespace, QString{}},
            Token{TokenType::DecimalInteger, QString{"1"}},
        };

        Tokenizer tokenizer{Specification::Version_1_1};
        tokenizer.startWithStream(inputStream);
        for (int i = 0; i < expectedTokens.size(); ++i) {
            expectedToken = expectedTokens.at(i);
            token = tokenizer.read();
            REQUIRE(token == expectedToken);
        }
    }

    TAGS(output-all-tokens)
    SKIP_BY_DEFAULT()
    void printAllTokens() {
        // That's no real test. It just outputs the read tokens to update the test above.
        auto filePath = unitTestExecutablePath().parent_path() / "data" / "Tokenizer" / "all_tokens.toml";
        auto filePathQt = QString::fromStdString(filePath.string());
        auto inputStream = InputStream::createFromFile(filePathQt);
        Tokenizer tokenizer{Specification::Version_1_1};
        tokenizer.startWithStream(inputStream);
        token = tokenizer.read();
        while (token.type() != TokenType::EndOfDocument) {
            QString log = "Token{TokenType::";
            log.append(erbsland::qt::toml::impl::tokenTypeToString(token.type()));
            log.append(", ");
            if (token.text().isEmpty()) {
                log.append("QString{}");
            } else {
                log.append("QString{\"");
                auto text = token.text();
                text.replace("\\", "\\\\");
                text.replace("\n", "\\n");
                text.replace("\r", "\\r");
                text.replace("\b", "\\b");
                text.replace("\f", "\\f");
                text.replace("\t", "\\t");
                text.replace("\"", "\\\"");
                log.append(text);
                log.append("\"}");
            }
            log.append("},");
            consoleWriteLine(log.toStdString());
            token = tokenizer.read();
        }
    }
};